import os
import sys
import json
import urllib.request
import urllib.error
import glob
import random

# Configuration
VAULT_ROOT = r"c:/Users/chatg/Obsidian Vault/papa"
DAILY_DIR = os.path.join(VAULT_ROOT, "daily")
CLIPPINGS_DIR = os.path.join(VAULT_ROOT, "Clippings")
OUTPUT_PROFILE = os.path.join(VAULT_ROOT, "Templates", "Motoyama_Profile.md")

OLLAMA_API_URL = "http://localhost:11434/api/generate"
MODEL_NAME = "llama3"

# Analysis System Prompt
ANALYSIS_PROMPT = """
You are an expert AI Psychologist and Linguist.
Your task is to analyze the following text samples written by "Motoyama Takahiro".
Extract the essence of his personality and writing style to create a "Persona Profile".

## Output Format (Markdown)
1.  **Values (価値観)**: What does he care about? (e.g., Efficiency, Freedom, Money).
2.  **Writing Style (文体)**: Tone (Casual/Formal), Sentence length, distinct phrases.
3.  **Keywords (口癖)**: Specific words he uses often.
4.  **Thinking Pattern (思考の癖)**: How does he approach problems?
5.  **Instruction for AI**: A short prompt instructing an AI how to act like him.

## Text Samples
"""

def get_text_samples():
    """Reads recent daily notes and random clippings."""
    samples = []
    
    # Get recent 3 daily notes
    daily_files = sorted(glob.glob(os.path.join(DAILY_DIR, "*.md")), reverse=True)[:3]
    for p in daily_files:
        try:
            with open(p, 'r', encoding='utf-8') as f:
                samples.append(f"--- Source: {os.path.basename(p)} ---\n" + f.read()[:1000])
        except Exception: 
            pass

    # Get random 3 clippings (if available)
    clipping_files = glob.glob(os.path.join(CLIPPINGS_DIR, "*.md"))
    if clipping_files:
        for p in random.sample(clipping_files, min(len(clipping_files), 3)):
            try:
                with open(p, 'r', encoding='utf-8') as f:
                    samples.append(f"--- Source: {os.path.basename(p)} ---\n" + f.read()[:1000])
            except Exception:
                pass
                
    return "\n\n".join(samples)

def query_ollama(prompt):
    data = {
        "model": MODEL_NAME,
        "prompt": prompt,
        "stream": True
    }
    
    headers = {'Content-Type': 'application/json'}
    req = urllib.request.Request(
        OLLAMA_API_URL, 
        data=json.dumps(data).encode('utf-8'), 
        headers=headers
    )

    full_response = ""
    print(f"\n🧠 {MODEL_NAME} is analyzing Motoyama's digital footprint...\n")
    print("-" * 50)

    try:
        with urllib.request.urlopen(req) as response:
            for line in response:
                if line:
                    decoded_line = line.decode('utf-8')
                    try:
                        json_obj = json.loads(decoded_line)
                        chunk = json_obj.get("response", "")
                        print(chunk, end='', flush=True)
                        full_response += chunk
                        if json_obj.get("done", False):
                            break
                    except json.JSONDecodeError:
                        continue
    except urllib.error.URLError as e:
        print(f"\n\n🛑 Error connecting to Ollama: {e}")
        return None
        
    print("\n" + "-" * 50)
    return full_response

def main():
    print("=== 👤 Persona Trace Module ===")
    print("あなたの過去のログ(日記・クリップ)を分析し、「自分自身の分身プロファイル」を生成します。\n")
    
    samples = get_text_samples()
    if not samples:
        print("テキストサンプルが見つかりませんでした。日誌やクリッピングフォルダを確認してください。")
        input()
        return

    final_prompt = ANALYSIS_PROMPT + samples
    
    result = query_ollama(final_prompt)
    
    if result:
        # Wrap in a Persona Prompt format
        final_output = f"""# System Prompt: Motoyama Persona
        
This profile is auto-generated by `trace_user.py` based on recent logs.
Use this to instruct other agents (SNS, Content) to mimic the user.

{result}
"""
        
        with open(OUTPUT_PROFILE, 'w', encoding='utf-8') as f:
            f.write(final_output)
            
        print(f"\n✅ プロファイルを更新しました: {OUTPUT_PROFILE}")

    print("\nPress Enter to exit...")
    input()

if __name__ == "__main__":
    main()
